
project_id = "azitogggugktqavcnvbn"

[functions.collect-market-data]
verify_jwt = false

[functions.get-available-assets]
verify_jwt = false

[functions.generate-ai-insights]
verify_jwt = false

[functions.process-alerts]
verify_jwt = false

[functions.send-test-whatsapp]
verify_jwt = false

[functions.collect-social-sentiment]
verify_jwt = false

[functions.collect-news]
verify_jwt = false

[functions.generate-news-summaries]
verify_jwt = false
