// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azitogggugktqavcnvbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6aXRvZ2dndWdrdHFhdmNudmJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjE2MTcsImV4cCI6MjA2OTYzNzYxN30.wXMq1qXKxQ70zLVqVp-fXK9D7j03kWkgFh1HSVJtk_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});